apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: new-pipeline
spec:
  params:
    - default: 'https://github.com/wpernath/quarkus-simple.git'
      description: Source to the GIT
      name: git-url
      type: string
    - default: main
      description: revision to be used
      name: git-revision
      type: string
    - name: image-name
      type: string
      description: the name of the target image including registry
      default: quay.io/wpernath/quarkus-simple-wow:latest
    - name: image-username
      type: string
      description: the username you use to access the registry
    - name: image-password
      type: string
      description: The password you use to access the registry
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: compile
      params:
        - name: GOALS
          value:
            - compile
            - '-DskipTests'
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: maven-caching
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-repo
          workspace: maven-repo
        - name: maven-settings
          workspace: maven-settings
    - name: package
      params:
        - name: GOALS
          value:
            - package
            - '-DskipTests'
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - compile
      taskRef:
        kind: Task
        name: maven-caching
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-repo
          workspace: maven-repo
        - name: maven-settings
          workspace: maven-settings
    - name: builld-image
      params:
        - name: GOALS
          value:
            - package
            - '-DskipTests'
            - '-Dquarkus.container-image.build=true'
            - '-Dquarkus.container-image.push=true'
            - '-Dquarkus.container-image.builder=jib'
            - >-
              -Dquarkus.container-image.image=$(params.image-name)
            - '-Dquarkus.container-image.username=$(params.image-username)'
            - >-
              -Dquarkus.container-image.password=$(params.image-password)
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - package
      taskRef:
        kind: Task
        name: maven-caching
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-repo
          workspace: maven-repo
        - name: maven-settings
          workspace: maven-settings
  workspaces:
    - name: shared-workspace
      optional: false
    - name: maven-settings
      optional: false
    - name: maven-repo
      optional: false
