apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: new-pipeline
spec:
  params:
    - default: 'http://gogs.ci.svc:3000/quarkus-simple.git'
      description: Source to the GIT
      name: git-url
      type: string
    - default: main
      description: revision to be used
      name: git-revision
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven
      params:
        - name: MAVEN_IMAGE
          value: >-
            gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
        - name: GOALS
          value:
            - compile
            - "-DskipTests"
        - name: MAVEN_MIRROR_URL
          value: 'http://nexus.ci.svc:8081/repository/maven-public'
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: maven-caching
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-repo
          workspace: maven-repo
        - name: maven-settings
          workspace: maven-settings
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: maven-repo
  
