namePrefix: dev-  
commonLabels:
  variant: development

bases:
- ../../base

# replace the image tag of the container with latest
images:
  - name: quay.io/wpernath/simple-quarkus
    newTag: latest

# apply a patch to replace the Host of the Route
patches:
#- patch: |-
#    - op: replace
#      path: /spec/host
#      value: art-test.apps-crc.testing
#  target:
#    kind: Route
# this patch needs to be done, because kustomize does not change 
# the route target service name
- patch: |-
    - op: replace
      path: /spec/to/name
      value: dev-simple
  target:
    kind: Route
