# permissions for end users to view quarkussimples.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quarkussimple-viewer-role
rules:
- apiGroups:
  - charts.wanja.org
  resources:
  - quarkussimples
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.wanja.org
  resources:
  - quarkussimples/status
  verbs:
  - get
