# permissions for end users to edit quarkussimples.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quarkussimple-editor-role
rules:
- apiGroups:
  - charts.my.domain
  resources:
  - quarkussimples
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.my.domain
  resources:
  - quarkussimples/status
  verbs:
  - get
