apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simple          
    spec:
      containers:
      - image: quay.io/wpernath/simple-quarkus:stage
        imagePullPolicy: Always
        name: simple
        ports:
        - containerPort: 8080
          protocol: TCP
