apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: staging-  
commonLabels:
  variant: staging
commonAnnotations:
  note: We are on staging now
bases:
- ../../base
patchesStrategicMerge:
  - deployment.yaml
  - route.yaml

