apiVersion: charts.my.domain/v1alpha1
kind: QuarkusSimple
metadata:
  name: quarkussimple-sample
spec:
  # Default values copied from <project_dir>/helm-charts/quarkus-simple/values.yaml
  config:
    greeting: This needs to be changed per stage!
  deployment:
    image: quay.io/wpernath/simple-quarkus
    includeHealthChecks: true
    replicas: 1
    version: latest
  route:
    host: simple-article-helm.apps-crc.testing
  
  
